name: twitter
description: "From breaking news and entertainment to sports and politics, get the full story with all the live commentary."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-0.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  provider: ^6.1.1
  jwt_decode: ^0.3.1
  url_launcher: ^6.2.1
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  page_transition: ^2.1.0
  full_screen_image: ^2.0.0
  vector_graphics: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.5
  vector_graphics_compiler: ^1.1.9+2

flutter:
  assets:
    - assets/images/
    - assets/icons/compiled/
  fonts:
    - family: Chirp
      fonts:
        - asset: assets/fonts/chirp-bold.ttf
          weight: 700
        - asset: assets/fonts/chirp-medium.ttf
          weight: 500
        - asset: assets/fonts/chirp-regular.ttf
  uses-material-design: true

flutter_native_splash:
  color: "#1d9bf0"
  image: assets/icon.png
  android_12:
    image: assets/icon.png
    color: "#1d9bf0"
    icon_background_color: "#1d9bf0"
  android: true
  ios: true
  web: false